apiVersion: skaffold/v2beta17
kind: Config
metadata:
  name: appone
build:
  artifacts:
  - image: skaffold-example
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s-pod.yaml
